parameters:
    mindy.mail.from: []
    mindy.mail.reply_to: []
    mindy.mail.subject_prefix: ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        \Swift_Events_SendListener:
            public: true
            tags: ['swiftmailer.default.plugin']

    Mindy\Bundle\MailBundle\:
        resource: '../../*'
        exclude: '../../{Tests,vendor}'

    Mindy\Bundle\MailBundle\SwiftMailer\Plugins\DefaultSenderPlugin:
        arguments:
            - '%mindy.mail.from%'
            - '%mindy.mail.reply_to%'

    Mindy\Bundle\MailBundle\SwiftMailer\Plugins\DefaultSubjectPrefixPlugin:
        arguments:
            - '%mindy.mail.subject_prefix%'

    Mindy\Bundle\MailBundle\Helper\Mail:
        public: true

    mindy.bundle.mail.helper.mail:
        alias: Mindy\Bundle\MailBundle\Helper\Mail
        public: true